name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: macos-10.15  
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: | 
          make
          make install
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            output
